//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventNowASP
{
    using System;
    using System.Collections.Generic;
    
    //public partial class Evento
    //{
    //    public int id { get; set; }
    //    public string titulo { get; set; }
    //    public string categoria { get; set; }
    //    public string imagen { get; set; }
    //    public string descripcion { get; set; }
    //    public string fecha { get; set; }
    //    public string horaI { get; set; }
    //    public string horaF { get; set; }
    //    public string ubicacion { get; set; }
    //    public string entidad { get; set; }
    //    public string tipo { get; set; }
    //    public System.DateTime AddedOn { get; set; }
    //}
}
